import type { DeviceTheme } from "app.contract.theme";

export const defaultTheme = {
  firstToolbarbutton: "#dfdede",
  // Main colors
  primaryColor: "#E07B4C",
  secondaryColor: "#D2691E",
  tertiaryColor: "#CD853F",
  // Container backgrounds
  themeSideMenu: "#FFFFFF",
  panelBackground: "#F8FAFC",
  // Tab
  tabSelection: "#E07B4C",
  activeTabBackground: "#FADDD1",
  activeTabText: "#E07B4C",
  activeTabBorder: "#E07B4C",
  activeTabFill: "#FADDD1",
  simpleTabText: "#333333",
  inactiveTabText: "#333333",
  // Buttons
  primaryButton: "#E07B4C",
  primaryButtonColor: "#FFFFFF",
  primaryButtonBorder: "#E07B4C",
  primaryButtonFill: "#E07B4C",
  secondaryButton: "#D2691E",
  secondaryButtonColor: "#FFFFFF",
  secondaryButtonBorder: "#D2691E",
  secondaryButtonFill: "#D2691E",
  tertiaryButtonColor: "#333333",
  buttonBorder: "#E1E3EA",
  // Scripture text
  bookHeadingColor: "#333333",
  chapterHeadingColor: "#333333",
  verseNumberColor: "#000000",
  verseTextColor: "#333333",
  pageBackground: "#FFFFFF",
  pageTextColor: "#333333",
  // Side menu
  heading1Color: "#333333",
  heading2Color: "#333333",
  heading3Color: "#333333",
  descriptionTextColor: "#666666",
  menuTextColor: "#333333",
  breadcrumbsColor: "#666666",
  sectionBackground: "#E07B4C",
  spaceNameColor: "#333333",
  sideMenuIconsColor: "#333333",
  selectedSpaceColor: "#E07B4C",
  unselectedSpaceColor: "#E1E3EA",
  spaceNameText: "#333333",
  addButtonBackground: "#E07B4C",
  addButtonIcon: "#FFFFFF",
  selectPanelIcon: "#333333",
  openCloseMenuIcon: "#333333",
  moreIcon: "#666666",
  settingsIcon: "#666666",
  inactiveSpaceIndicator: "#E1E3EA",
  activeSpaceIndicator: "#E07B4C",
  profileAvatar: "#E07B4C",
  // Selection UI & toolbar
  toolbarBorder: "#E1E3EA",
  toolbarFill: "#FFFFFF",
  toolbarIconsColor: "#333333",
  selectionUIBorder: "#E1E3EA",
  selectionUIFill: "#FFFFFF",
  selectionIconsColor: "#333333",
  toolbarBackground: "#FFFFFF",
  iconColor: "#333333",
  // Input fields
  inputTitleColor: "#333333",
  inputPlaceholderColor: "#999999",
  inputActiveBorder: "#E07B4C",
  inputActiveFill: "#FFFFFF",
  inputInactiveBorder: "#E1E3EA",
  inputInactiveFill: "#FFFFFF",
  inputBackground: "#FFFFFF",
  inputBorder: "#E1E3EA",
  inputText: "#333333",
  inputPlaceholder: "#999999",
  // Branding
  logoColor: "#333333",
  accentColor: "#E07B4C",
  // Space selection
  spaceSelection: "#E07B4C",
  // Text colors
  text1: "#333333",
  text2: "#666666",
  showTabIcons: true,
  "filter-mode": "invert(0)",
  primaryLight: "#FADDD1",
  onPrimaryLight: "#8B4513",
  primaryBase: "#E07B4C",
  onPrimaryBase: "#FFFFFF",
  primaryDark: "#C65D2D",
  onPrimaryDark: "#FFFFFF",
  secondaryLight: "#FFE4C4",
  onSecondaryLight: "#8B4513",
  secondaryBase: "#D2691E",
  onSecondaryBase: "#FFFFFF",
  secondaryDark: "#A0522D",
  onSecondaryDark: "#FFFFFF",
  tertiaryLight: "#FFEFD5",
  onTertiaryLight: "#8B4513",
  tertiaryBase: "#CD853F",
  onTertiaryBase: "#FFFFFF",
  tertiaryDark: "#A0522D",
  onTertiaryDark: "#FFFFFF",
  background: "#FFFFFF",
  onBackground: "#333333",
  surface: "#FAFAFA",
  onSurface: "#333333",
  text3: "#333333",
  "secondary-filter-mode": "invert(100%)",
};
export const darkTheme = {
  firstToolbarbutton: "#5C5C5C",
  // Main colors
  primaryColor: "#5A67D8",
  secondaryColor: "#A78BFA",
  tertiaryColor: "#34D399",
  // Container backgrounds
  themeSideMenu: "#2D2D2D",
  panelBackground: "#1A1A1A",
  // Tab
  tabSelection: "#5A67D8",
  activeTabBackground: "#404040",
  activeTabText: "#FFFFFF",
  activeTabBorder: "#5A67D8",
  activeTabFill: "#5A67D894",
  simpleTabText: "#AAAAAA",
  inactiveTabText: "#AAAAAA",
  // Buttons
  primaryButton: "#404040",
  primaryButtonColor: "#FFFFFF",
  primaryButtonBorder: "#5A67D8",
  primaryButtonFill: "#5A67D8",
  secondaryButton: "#5A67D8",
  secondaryButtonColor: "#FFFFFF",
  secondaryButtonBorder: "#5A67D8",
  secondaryButtonFill: "#5A67D8",
  tertiaryButtonColor: "#FFFFFF",
  buttonBorder: "#5A67D8",
  // Scripture text
  bookHeadingColor: "#FFFFFF",
  chapterHeadingColor: "#FFFFFF",
  verseNumberColor: "#FFFFFF",
  verseTextColor: "#FFFFFF",
  pageBackground: "#121212",
  pageTextColor: "#FFFFFF",
  // Side menu
  heading1Color: "#FFFFFF",
  heading2Color: "#FFFFFF",
  heading3Color: "#FFFFFF",
  descriptionTextColor: "#AAAAAA",
  menuTextColor: "#FFFFFF",
  breadcrumbsColor: "#AAAAAA",
  sectionBackground: "#5A67D8",
  spaceNameColor: "#FFFFFF",
  sideMenuIconsColor: "#FFFFFF",
  selectedSpaceColor: "#5A67D8",
  unselectedSpaceColor: "#666666",
  spaceNameText: "#FFFFFF",
  addButtonBackground: "#404040",
  addButtonIcon: "#5A67D8",
  selectPanelIcon: "#FFFFFF",
  openCloseMenuIcon: "#FFFFFF",
  moreIcon: "#AAAAAA",
  settingsIcon: "#AAAAAA",
  inactiveSpaceIndicator: "#666666",
  activeSpaceIndicator: "#5A67D8",
  profileAvatar: "#5A67D8",
  // Selection UI & toolbar
  toolbarBorder: "#FFFFFF24",
  toolbarFill: "#2D2D2D",
  toolbarIconsColor: "#FFFFFF",
  selectionUIBorder: "#FFFFFF24",
  selectionUIFill: "#2D2D2D",
  selectionIconsColor: "#FFFFFF",
  toolbarBackground: "#1A1A1A",
  iconColor: "#FFFFFF",
  "filter-mode": "invert(100%)",
  "secondary-filter-mode": "invert(0%)",
  // Input fields
  inputTitleColor: "#FFFFFF",
  inputPlaceholderColor: "#AAAAAA",
  inputActiveBorder: "#5A67D8",
  inputActiveFill: "#2D2D2D",
  inputInactiveBorder: "#666666",
  inputInactiveFill: "#2D2D2D",
  inputBackground: "#2D2D2D",
  inputBorder: "#666666",
  inputText: "#FFFFFF",
  inputPlaceholder: "#AAAAAA",
  // Branding
  logoColor: "#FFFFFF",
  accentColor: "#5A67D8",
  // Space selection
  spaceSelection: "#5A67D8",
  // Text colors
  text1: "#FFFFFF",
  text2: "#AAAAAA",
  showTabIcons: true,
  // Semantic colors
  primaryLight: "#93C5FD",
  onPrimaryLight: "#3B82F6",
  primaryBase: "#60A5FA",
  onPrimaryBase: "#111827",
  primaryDark: "#3B82F6",
  onPrimaryDark: "#FFFFFF",
  secondaryLight: "#C4B5FD",
  onSecondaryLight: "#8B5CF6",
  secondaryBase: "#A78BFA",
  onSecondaryBase: "#111827",
  secondaryDark: "#8B5CF6",
  onSecondaryDark: "#FFFFFF",
  tertiaryLight: "#6EE7B7",
  onTertiaryLight: "#10B981",
  tertiaryBase: "#34D399",
  onTertiaryBase: "#111827",
  tertiaryDark: "#FFFFFF",
  onTertiaryDark: "#10B981",
  background: "#0F172A",
  onBackground: "#FFFFFF",
  surface: "#1E293B",
  onSurface: "#FFFFFF",
  text3: "#F1F5F9",
};

/**
 * Gets the prefered color scheme from the browser.
 */
export function getPreferedColorScheme(): DeviceTheme {
  return window.matchMedia("(prefers-color-scheme: dark)").matches
    ? "dark"
    : "light";
}

/**
 * Get's the requested theme object.
 */
export function getThemeObject(theme: DeviceTheme) {
  return theme == "dark" ? darkTheme : defaultTheme;
}
